name: Deploy to AWS

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS and pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/apps/Portfolio-Frontend
            git pull origin main
